[build]
  publish = "./"                 # This is where your index.html is
  functions = "netlify/functions"  # Your serverless functions location

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
